### ISSUE TITLE
Error 500 after finishing the install

### ISSUE THREAD

**Issue by maeries** [Admidio/admidio#1208]
**Describe the bug**
When I go to the URL of my Admidio install I only get a Error 500.

**To Reproduce**
1. use this docker-compose.yml
```
version: '3.9'

services:
  db:
    restart: unless-stopped
    image: mariadb:10.5.8
    container_name: Admidio-MariaDB
    volumes:
      - "./data/database/config:/etc/mysql/conf.d"
      - "./data/database/data:/var/lib/mysql"
#    ports:
#      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=admidio
      - MYSQL_USER=admidio
      - MYSQL_PASSWORD=password

  admidio:
    restart: unless-stopped
    image: admidio/admidio:v4.0.4
    container_name: Admidio
    depends_on:
      - db
    volumes:
      - ./data/admidio/files:/opt/app-root/src/adm_my_files
      - ./data/admidio/themes:/opt/app-root/src/adm_themes
      - ./data/admidio/plugins:/opt/app-root/src/adm_plugins
    ports:
      - 8080:8080
    environment:
      - ADMIDIO_DB_TYPE=mysql
      - ADMIDIO_DB_HOST=db:3306
      - ADMIDIO_DB_NAME=admidio
      - ADMIDIO_DB_USER=admidio
      - ADMIDIO_DB_PASSWORD=secret-password
      #- ADMIDIO_DB_TABLE_PRAEFIX=adm
      #- ADMIDIO_MAIL_RELAYHOST=hostname.domain.at:25
      #- ADMIDIO_LOGIN_FOR_UPDATE=1
      #- ADMIDIO_ORGANISATION=ADMIDIO
      #- ADMIDIO_PASSWORD_HASH_ALGORITHM=DEFAULT
      #- ADMIDIO_ROOT_PATH=https://domain.tld/
      - TZ=Europe/Berlin
      #- HTTPD_START_SERVERS=8
      #- DOCUMENTROOT=/
      #- PHP_MEMORY_LIMIT=256M
      #- ERROR_REPORTING=E_ALL & ~E_NOTICE
      #- DISPLAY_ERRORS=ON
      #- DISPLAY_STARTUP_ERRORS=OFF
      #- TRACK_ERRORS=OFF
      #- HTML_ERRORS=ON
```
2. Fill in all the information (database, organization, user, etc.)
3. click "install admidio" and wait for it to finish
4. When asked for a donation click "later"
5. In Firefox you'll now see a white screen; Vivaldi will tell you it's an ERROR 500

**Expected behavior**
See a dashboard or login interface or something

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 96.0.3

**Additional context**
Log:
```
Admidio    | 172.18.0.8 - - [04/Feb/2022:23:46:32 +0100] "GET / HTTP/1.1" 303 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
Admidio    | [Fri Feb 04 23:46:32.261752 2022] [php7:error] [pid 94] [client 172.18.0.8:48924] PHP Fatal error:  Uncaught  --> Smarty: Unable to load template 'file:index.tpl' <-- \n  thrown in /opt/app-root/src/adm_program/libs/server/smarty/sysplugins/smarty_internal_template.php on line 195
Admidio    | 172.18.0.8 - - [04/Feb/2022:23:46:32 +0100] "GET /adm_program/overview.php HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
```
