### ISSUE TITLE
Zebra Striping Table

### ISSUE THREAD

**Issue by ximex** [Admidio/admidio#59]
Drop the old way to set `.odd` and `.even` classes on the `<tr>` and use the new CSS3 pseudo selector `:nth-child(...)` instead

http://caniuse.com/#feat=css-sel3

Only IE7 and IE8 needs the old way. I think at the release of 3.1 there is the usage of this browsers as low that we could drop the support of them

**Comment by ximex** [comment]
Ok found out the added classes to `<tr>` came from the datatable javascript.
So we only have to remove the code from the print.css or change it to the new selector style

**Comment by Fasse** [comment]
the odd and even in the print.css are from the dates module. There the print preview was not rewritten for Bootstrap. This should be done in a further version.

The print preview in the list module has the Bootstrap integration and should be the standard for the future dates module. 

So for now we should not change the print.css. If we have changed the dates module than there will be code removed.

**Comment by ximex** [comment]
#101 replaces the datatable lib with an other one

**Comment by Fasse** [comment]
Datatables has nothing to do with this issue. Even and odd are used in an print table.

**Comment by ximex** [comment]
no. the zebra effect in print mode is made by the css classes of bootstrap
```css
.table-striped > tbody > tr:nth-of-type(2n+1) {
    background-color: #F9F9F9;
}
```
this code in print.css Line 60 isn't used anywhere
```css
/* Settings for background colors of table rows */
.even {
    background-color: #eeeeee;
}
.odd {
    background-color: #ffffff;
}
```
and in the normal tables there is no zebra effect. there are only `.odd` and `.even` classes on the `<tr>` but no css style that mach this selector

if we want this style on the normal tables too we have to set the css class `.table-striped` on the `<table>`. then the bootstrap default zebra style will effect the table.

the `.odd` and `.even` classes are generated by javascript code of the datatable lib
